# Generated by Django 4.1 on 2023-07-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_inf', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='data published')),
                ('available_quantity', models.IntegerField(default=1)),
                ('total_quantity', models.IntegerField(default=1)),
                ('borrow_times', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/cover_images')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=8)),
                ('borrow_date', models.DateField()),
                ('reture_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
