# Generated by Django 4.1 on 2023-07-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_major_inf_major_rename_school_inf_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_times',
            field=models.IntegerField(default=0, max_length=10000),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='isreturned',
            field=models.BooleanField(default=False),
        ),
    ]
