# Generated by Django 4.1 on 2023-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrow_times_borrowrecord_isreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_all_return_db',
            field=models.BooleanField(default=False),
        ),
    ]
