# Generated by Django 4.1 on 2023-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_borrow_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_all_return_db',
            field=models.BooleanField(default=True),
        ),
    ]
