# Generated by Django 4.1 on 2023-07-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_student_is_all_return_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrow_times',
            new_name='borrow_times_db',
        ),
        migrations.AddField(
            model_name='student',
            name='borrow_times_db',
            field=models.IntegerField(default=0),
        ),
    ]
